name: flutter_framework
description: Flutter framework bound components implementations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  estd:
    path: ../../../backend/estd
  domain:
    path: ../../../backend/domain
  infrastructure:
    path: ../../../backend/infrastructure
  built_collection: 4.3.2
  provider: 4.1.3
  flutter_tts: 1.2.3
  cloud_firestore: 0.13.7
  firebase_auth: 0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_estd:
    path: ../../../backend/test_estd
  mockito: 4.1.1
