name: bloc
description: Bloc-backed state management for the applications' backend

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  domain:
    path: ../../../backend/domain
  infrastructure:
    path: ../../../backend/infrastructure
  estd:
    path: ../../../backend/estd
  meta: 1.1.8
  built_collection: 4.3.2
  optional: 5.0.0
  rxdart: 0.24.1
  equatable: 1.2.0
  tuple: 1.0.3

dev_dependencies:
  test: ^1.14.0
  mockito: 4.1.1
  test_estd:
    path: ../../../backend/test_estd
