name: bloc
description: Bloc-backed state management for the applications' backend

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  domain:
    path: ../../../backend/domain
  estd:
    path: ../../../backend/estd
  built_collection: 4.3.2
