name: flutter_gateway
description: Flutter-specific gateways implementation

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../../../domain
  cloud_firestore: 0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

