name: childspeak
description: Web & mobile application aimed to help children to start speaking
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  estd:
    path: ../../../../../../backend/estd
  presentation:
    path: ../../../../../presentation
  domain:
    path: ../../../../../../backend/domain
  infrastructure:
    path: ../../../../../../backend/infrastructure
  bloc:
    path: ../../../../../state_management/bloc
  flutter_framework:
    path: ../../../../../framework/flutter_framework
  built_collection: 4.3.2
  intl: 0.16.1
  provider: 4.1.3
  flutter_tts: 1.2.3
  firebase_core: 0.4.5
  firebase_auth: 0.16.1
  cloud_firestore: 0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: 0.17.9

flutter:
  uses-material-design: true
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: asset/font/BalsamiqSans-Regular.ttf
        - asset: asset/font/BalsamiqSans-Italic.ttf
          style: italic
        - asset: asset/font/BalsamiqSans-Bold.ttf
          weight: 700
        - asset: asset/font/BalsamiqSans-BoldItalic.ttf
          weight: 700
          style: italic
