name: childspeak
description: Web & mobile application aimed to help children to start speaking
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  estd:
    path: ../../../../../../backend/estd
  presentation:
    path: ../../../../../presentation
  domain:
    path: ../../../../../../backend/domain
  bloc:
    path: ../../../../../state_management/bloc
  flutter_gateway:
    path: ../../../../../../backend/driver/gateway/flutter_gateway
  flutter_framework:
    path: ../../../../../framework/flutter_framework
  intl: 0.16.1
  firebase_core: 0.4.5
  cloud_firestore: 0.13.7
  built_collection: 4.3.2
  provider: 4.1.3
  flutter_tts: 1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: 0.17.9

flutter:
  uses-material-design: true
